import sounddevice as sd
from package_algorithms.module_audiofile_functions import *
import soundfile as sf
class AudioMeasurement:

    def __init__(self,
                 name_measurement,
                 filepath_audiofile,
                 delay,
                 id_output_device,
                 id_input_device,
                 filepath_recordfile):
        self.name_measurement = name_measurement
        self.filepath_audiofile = filepath_audiofile
        self.delay = delay
        self.id_measurement = ''
        self.autogenerated_name_measurement = ''
        self.time_of_measurement = ''
        self.infos = ''
        self.id_output_device = id_output_device
        self.id_input_device = id_input_device
        self.filepath_recordfile = filepath_recordfile



    class AudioDevice:
        def __init__(self):
            self.x_position = 0
            self.y_position = 0
            self.settings = 0
            self.infos = ''





    def start_audio_measurement(self):

        print("The audio measurement has been startet!")

        # Öffnen der Messungsinstanz der betreffenden Messung


        # Abfrage aller Testparameter

        # open_newemeasurenment


        # Abfrage aller angeschlossenen Geräte

        print(sd.query_devices())

        #usb_sound_card_indices = list(filter(lambda x: x is not False,
         #                                    map(get_device_number_if_usb_soundcard,
         #                                        [index_info for index_info in enumerate(sd.query_devices())])))

        # Abgleich aller angeschlossenen Audiogeräte mit der in der Messungsinstanz definierten Audiogeräte

        # Überprüfen ob in Messungsinstanz definiertes Mischprogramm intalliert ist

        # Starten des definierten Mischprogramms

        # Überprüfen, ob Einstellungen für das Mischprogramm gefunden und geöffnet werden können.

        # Abspielen der Audiodateien und Aufnahme (zeitgleich ud synchronisiert)

        #sd.play(data='',samplerate=None,mapping=[0,1,2,3,4], blocking=False, loop=False, kwaargs**)
        #sd.play(data='C:\\Users\\Tobi_SurfacePro\\PycharmProjects\\AudioToolBox\\directory_audio_file\\Jungle Windows Start.wav', samplerate=None, mapping=[8], blocking=False, loop=False)

        data, fs = sf.read(self.filepath_audiofile)

        sd.play(data, fs, device=self.id_output_device)

        sd.wait()

        #sd.rec(frames=None, samplerate=fs, channels=None)


        print("Playrec")

        print(data)

        sd.default.samplerate = 48000
        sd.default.channels = 2
        myrecording = sd.playrec(data)

        #sf.write('output11111.wav', myrecording, fs)
        sf.write(self.filepath_recordfile, myrecording, fs)



        # Speichern der Aufnahmen in Messungsinstanz oder in definierten Ordner
        data_record, fs = sf.read(self.filepath_recordfile)

        sd.play(data_record, fs)
        sd.wait()



        return 0

